modLoader="javafml"
loaderVersion="[36,)"
license="LGPL-v3"

[[mods]]
modId="leftclickandshoot"
version="${file.jarVersion}"
displayName="LeftClickAndShoot"
authors="TeamPotato"
description='''
A Minecraft mod.
'''